### ISSUE TITLE
CH Core Composition Profile EPR - Sections ordered (oe, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-core#115]
ch.fhir.ig.ch-core#2.0.0 /StructureDefinition-ch-core-composition-epr.html

Sections should have a fix order as it is in CDA.

Currently it is defined open and if a dependent profile it is set to ordered it will not work:

Unable to generate snapshot for http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-composition-medicationcard in /Users/oliveregger/Documents/github/ch-emed/input/resources/structuredefinition/ch-emed-composition-medicationcard

see also issue https://github.com/ehealthsuisse/ch-emed/issues/57

oe, ahdis

**Comment by oliveregger** [comment]
if it the ordering is fixed, dependent profiles can only append sections, this causes a problem since in CDA the originalRepresentation is at the end.

**Comment by oliveregger** [comment]
Caused by: org.hl7.fhir.exceptions.FHIRException: Unable to generate snapshot for http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-composition-medicationcard in /Users/oliveregger/Documents/github/ch-emed/input/resources/structuredefinition/ch-emed-composition-medicationcard
        at org.hl7.fhir.igtools.publisher.Publisher.generateSnapshot(Publisher.java:4642)
        at org.hl7.fhir.igtools.publisher.Publisher.generateSnapshots(Publisher.java:4591)
        ... 4 more
Caused by: org.hl7.fhir.exceptions.DefinitionException: Named items are out of order in the slice

**Comment by oliveregger** [comment]
only solution would be to remove the slicing of the section in CompositionEPR, otherwise we cannot add the section at the end in dependent profiles

**Comment by oliveregger** [comment]
tooling issue, not an issue or ch-core at the moment, will retract that issue
